image: docker:latest
services:
  - docker:dind

workflow:
  rules:
    - changes:
        - helm/**/*
        - helm/*
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'

stages: 
  - npm-build
  - package
  - deploy
  - cleanup

npm-build:
  image: node:16.14.0-alpine
  stage: npm-build
  script:
    - "npm install"
    - "npm run build:dev"
  artifacts:
    paths:
      - dist/*

docker-build:
  stage: package
  script:
    - docker build -t $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_SHA -t $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:latest .

docker-deploy:
  stage: deploy
  script:
  - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD $CI_HARBOR_URL
  - docker push $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  - docker push $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:latest

cleanup_job:
  stage: cleanup
  script:
    - docker rmi $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker rmi $CI_HARBOR_URL/$CI_HARBOR_PROJECT/$CI_PROJECT_NAME:latest
  when: always
