apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldc-web-mobile
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: ldc-web-mobile=harbor.digitallina.com/develop-ldc/ldc-web-mobile
    argocd-image-updater.argoproj.io/ldc-web-mobile.pull-secret: pullsecret:argocd/harbor-creds
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/ldc-web-mobile.update-strategy: latest
    argocd-image-updater.argoproj.io/ldc-web-mobile.allow-tags: 'regexp:^[a-z0-9]+$'
    argocd-image-updater.argoproj.io/ldc-web-mobile.ignore-tags: "latest"
    argocd-image-updater.argoproj.io/git-branch: develop
spec:
  project: default
  source:
    repoURL: 'https://git.digitallina.com/ldc/web/ldc-web-mobile.git'
    path: helm/charts
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service-ldc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-ldc-web-mobile
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git.digitallina.com/ldc/web/ldc-web-mobile.git
